# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 15.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: npm install, build, and test
      run: |
        npm install
        npm test
        npm run build --if-present
    - name: Archive production artifacts
      uses: actions/upload-artifact@v2
      with:
        name: api-build
        path: |
          dist
          !dist/**/*.md
        retention-days: 5
    - name: Download api-build artifact
      uses: actions/download-artifact@v2
      with:
        name: api-build
    - name: Deploy api to hosting
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER_NAME }}
        password: ${{ secrets.SSH_PASSWORD }}
        script: |
          sudo rm -rf /var/www/api.hiiamsi.com/html/node-typescript-eslint-prettier-boilerplate
          ${{ secrets.SSH_PASSWORD }}
          cd /var/www/api.hiiamsi.com/html
          sudo git clone git@github.com:anhtuanpro6420/node-typescript-eslint-prettier-boilerplate.git
          sudo -u nodejs pm2 stop server
          sudo npm install
          sudo npm run build
          sudo -u nodejs pm2 start /var/www/api.hiiamsi.com/html/node-typescript-eslint-prettier-boilerplate/dist/server.js
          sudo -u nodejs pm2 save
          echo 'Deployment successfully'
